"use client";

import { useState, useCallback, useRef, useEffect } from "react";
import { createPortal } from "react-dom";
import { RefreshCw, Download, Loader2, Sparkles, ImageIcon, Check, Link, Copy, Share2, X, Hash, MessageSquare } from "lucide-react";
import type { ComicStory, ComicTone, TripSummary } from "@/types";
import type { SharePayload } from "@/types/integrations";
import ComicPanelCard from "@/components/ComicPanelCard";
import ToneSelector from "@/components/ToneSelector";

interface ComicStoryRendererProps {
  story: ComicStory | null;
  trip: TripSummary | null;
  loading: boolean;
  generating: boolean;
  enriching?: boolean;
  tone: ComicTone;
  onToneChange: (tone: ComicTone) => void;
  onRegenerate: (tone: ComicTone) => void;
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

const SCENE_LABELS: Record<string, string> = {
  opening: "Departure",
  journey: "On the Road",
  highlight: "Highlight",
  arrival: "Arrival",
};

function buildExportText(story: ComicStory, trip: TripSummary | null): string {
  const divider = "─".repeat(52);
  const header = [
    divider,
    "  FLEETHAPPENS · TRIP STORY",
    divider,
    "",
    `  ${story.title}`,
    "",
    trip ? `  Vehicle : ${trip.deviceName}` : "",
    trip ? `  Date    : ${new Date(trip.start).toLocaleDateString("en-US", { weekday: "long", year: "numeric", month: "long", day: "numeric" })}` : "",
    trip ? `  Distance: ${trip.distanceKm ?? (trip.distanceMeters / 1000).toFixed(1)} km` : "",
    trip ? `  Avg Spd : ${trip.averageSpeedKmh} km/h  ·  Max: ${trip.maxSpeedKmh} km/h` : "",
    `  Tone    : ${story.tone}`,
    "",
    divider,
    "",
  ].filter(Boolean);

  const panels = story.panels.map((panel) => {
    const sceneLabel = SCENE_LABELS[panel.sceneType] ?? panel.sceneType;
    const lines = [
      `  PANEL ${panel.panelNumber.toString().padStart(2, "0")}  ·  ${sceneLabel.toUpperCase()}`,
      `  ${panel.locationName}`,
      "",
      `  ${panel.caption}`,
    ];
    if (panel.speechBubble) lines.push("", `  "${panel.speechBubble}"`);
    const stats: string[] = [];
    if (panel.timeLabel)     stats.push(panel.timeLabel);
    if (panel.distanceLabel) stats.push(panel.distanceLabel);
    if (panel.speedLabel)    stats.push(panel.speedLabel);
    if (panel.dwellLabel)    stats.push(panel.dwellLabel);
    if (stats.length) lines.push("", `  ${stats.join("  ·  ")}`);
    lines.push("", divider, "");
    return lines.join("\n");
  });

  const footer = [
    "",
    `  Generated by FleetHappens  ·  ${new Date(story.createdAt).toLocaleString()}`,
    `  Powered by Geotab Direct API + Ace`,
    "",
  ].join("\n");

  return header.join("\n") + "\n" + panels.join("\n") + footer;
}

function PanelSkeleton({ index }: { index: number }) {
  const colors = ["#38bdf8", "#34d399", "#f5a623", "#a78bfa"];
  const color  = colors[index % colors.length];
  return (
    <div className="rounded-2xl overflow-hidden bg-[#0f1319] border border-[rgba(255,255,255,0.07)] animate-fade-up" style={{ animationDelay: `${index * 80}ms` }}>
      <div className="h-[2.5px]" style={{ background: color, opacity: 0.6 }} />
      <div className="p-5 min-h-[240px] flex flex-col justify-end space-y-3">
        <div className="h-2.5 w-16 rounded skeleton-shimmer" />
        <div className="h-px w-full skeleton-shimmer" />
        <div className="h-4 w-full rounded skeleton-shimmer" />
        <div className="h-4 w-4/5 rounded skeleton-shimmer" />
        <div className="h-10 w-3/5 rounded-2xl skeleton-shimmer" />
      </div>
      <div className="bg-[rgba(0,0,0,0.3)] px-5 py-3 flex gap-4 border-t border-[rgba(255,255,255,0.05)]">
        <div className="h-2.5 w-14 rounded skeleton-shimmer" />
        <div className="h-2.5 w-14 rounded skeleton-shimmer" />
      </div>
    </div>
  );
}

// ─── Toast ────────────────────────────────────────────────────────────────────

type ToastState = { msg: string; kind: "success" | "info" } | null;

function InlineToast({ toast }: { toast: ToastState }) {
  if (!toast) return null;
  return (
    <div className="fixed bottom-6 left-1/2 -translate-x-1/2 z-50 pointer-events-none animate-fade-up">
      <div className={`flex items-center gap-2 px-4 py-2.5 rounded-xl shadow-[0_8px_32px_rgba(0,0,0,0.6)] text-[13px] font-body font-semibold border backdrop-blur-md ${
        toast.kind === "success"
          ? "bg-[rgba(52,211,153,0.12)] border-[rgba(52,211,153,0.25)] text-[#34d399]"
          : "bg-[rgba(56,189,248,0.12)] border-[rgba(56,189,248,0.25)] text-[#38bdf8]"
      }`}>
        <Check className="h-3.5 w-3.5 shrink-0" />
        {toast.msg}
      </div>
    </div>
  );
}

// ─── Main component ───────────────────────────────────────────────────────────

export default function ComicStoryRenderer({
  story, trip, loading, generating, enriching = false, tone, onToneChange, onRegenerate,
}: ComicStoryRendererProps) {
  const [pendingTone, setPendingTone] = useState<ComicTone>(tone);
  const [toast, setToast] = useState<ToastState>(null);
  const [shareOpen, setShareOpen] = useState(false);
  const [shareRect, setShareRect] = useState<DOMRect | null>(null);
  const [exporting, setExporting] = useState(false);
  const [sharing, setSharing] = useState<"slack" | "teams" | null>(null);
  const [shareMessage, setShareMessage] = useState("");
  const shareButtonRef = useRef<HTMLButtonElement>(null);
  const sharePopoverRef = useRef<HTMLDivElement>(null);

  const handleToneChange = (t: ComicTone) => { setPendingTone(t); onToneChange(t); };
  const handleRegenerate = () => onRegenerate(pendingTone);

  const showToast = useCallback((msg: string, kind: "success" | "info" = "success") => {
    setToast({ msg, kind });
    setTimeout(() => setToast(null), 2800);
  }, []);

  // Close share popover when clicking outside button or popover
  useEffect(() => {
    if (!shareOpen) return;
    function onPointerDown(e: PointerEvent) {
      const target = e.target as Node;
      const inButton = shareButtonRef.current?.contains(target);
      const inPopover = sharePopoverRef.current?.contains(target);
      if (!inButton && !inPopover) setShareOpen(false);
    }
    document.addEventListener("pointerdown", onPointerDown);
    return () => document.removeEventListener("pointerdown", onPointerDown);
  }, [shareOpen]);

  const handleCopyLink = useCallback(async () => {
    const url = typeof window !== "undefined" ? window.location.href : "";
    try {
      await navigator.clipboard.writeText(url);
      showToast("Link copied to clipboard!", "success");
    } catch {
      showToast("Could not copy link", "info");
    }
    setShareOpen(false);
  }, [showToast]);

  const handleCopyText = useCallback(async () => {
    if (!story) return;
    try {
      await navigator.clipboard.writeText(buildExportText(story, trip));
      showToast("Story text copied!", "success");
    } catch {
      showToast("Could not copy text", "info");
    }
    setShareOpen(false);
  }, [story, trip, showToast]);

  const handleExport = useCallback(async () => {
    if (!story) return;
    setExporting(true);

    try {
      const res = await fetch("/api/story/export-pdf", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ story, trip }),
      });

      if (!res.ok) {
        const err = await res.json().catch(() => ({}));
        throw new Error((err as { error?: string }).error ?? "PDF generation failed");
      }

      const blob = await res.blob();
      const url  = URL.createObjectURL(blob);
      const a    = document.createElement("a");
      const dateStr  = trip
        ? new Date(trip.start).toISOString().slice(0, 10)
        : new Date(story.createdAt).toISOString().slice(0, 10);
      const safeName = story.title.replace(/[^a-z0-9]+/gi, "-").toLowerCase().slice(0, 40);
      a.href     = url;
      a.download = `fleethappens-story-${safeName}-${dateStr}.pdf`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
      showToast("PDF exported!", "success");
    } catch {
      showToast("Export failed — please try again", "info");
    } finally {
      setExporting(false);
    }
  }, [story, trip, showToast]);

  const buildSharePayload = useCallback((): SharePayload | null => {
    if (!story) return null;
    const metrics: SharePayload["metrics"] = [];
    if (trip) {
      const dist = trip.distanceKm ?? (trip.distanceMeters / 1000).toFixed(1);
      metrics.push({ label: "Distance", value: `${dist} km` });
      metrics.push({ label: "Avg Speed", value: `${trip.averageSpeedKmh} km/h` });
      metrics.push({ label: "Max Speed", value: `${trip.maxSpeedKmh} km/h` });
      metrics.push({ label: "Vehicle", value: trip.deviceName });
    }
    metrics.push({ label: "Panels", value: String(story.panels.length) });
    metrics.push({ label: "Tone", value: story.tone });

    const firstCaption = story.panels[0]?.caption ?? "";
    const summary = firstCaption
      ? firstCaption.slice(0, 180) + (firstCaption.length > 180 ? "…" : "")
      : `A ${story.tone} trip story generated by FleetHappens.`;

    return {
      title: story.title,
      summary,
      metrics,
      linkUrl: typeof window !== "undefined" ? window.location.href : "",
      source: "story",
      userMessage: shareMessage.trim() || undefined,
      pdfContext: { type: "story" as const, story, trip },
    };
  }, [story, trip, shareMessage]);

  const handleShareToSlack = useCallback(async () => {
    const payload = buildSharePayload();
    if (!payload) return;
    setSharing("slack");
    setShareOpen(false);
    try {
      const res = await fetch("/api/integrations/slack/share", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(payload),
      });
      const json = await res.json() as { ok: boolean; data?: { message: string; mock?: boolean }; error?: string };
      if (!json.ok) throw new Error(json.error ?? "Slack share failed");
      const msg = json.data?.mock
        ? "Shared (demo mode) — configure SLACK_WEBHOOK_URL to send for real"
        : json.data?.message ?? "Shared to Slack";
      showToast(msg, json.data?.mock ? "info" : "success");
      setShareMessage("");
    } catch (err) {
      showToast(err instanceof Error ? err.message : "Could not share to Slack", "info");
    } finally {
      setSharing(null);
    }
  }, [buildSharePayload, showToast]);

  const handleShareToTeams = useCallback(async () => {
    const payload = buildSharePayload();
    if (!payload) return;
    setSharing("teams");
    setShareOpen(false);
    try {
      const res = await fetch("/api/integrations/teams/share", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(payload),
      });
      const json = await res.json() as { ok: boolean; data?: { message: string; mock?: boolean }; error?: string };
      if (!json.ok) throw new Error(json.error ?? "Teams share failed");
      const msg = json.data?.mock
        ? "Shared (demo mode) — configure TEAMS_WEBHOOK_URL to send for real"
        : json.data?.message ?? "Shared to Microsoft Teams";
      showToast(msg, json.data?.mock ? "info" : "success");
      setShareMessage("");
    } catch (err) {
      showToast(err instanceof Error ? err.message : "Could not share to Teams", "info");
    } finally {
      setSharing(null);
    }
  }, [buildSharePayload, showToast]);

  return (
    <div className="space-y-8 pb-20">
      <InlineToast toast={toast} />

      {/* Story title + actions */}
      {story && (
        <div className="flex items-start justify-between gap-4 animate-fade-up">
          <div>
            <div className="flex items-center gap-2 mb-1.5">
              <Sparkles className="h-4 w-4 text-[#fb923c]" />
              <h2 className="font-display font-extrabold text-2xl text-white tracking-tight leading-tight">
                {story.title}
              </h2>
            </div>
            {trip && (
              <p className="text-sm text-[rgba(232,237,248,0.38)] font-data">
                {trip.deviceName} · {new Date(trip.start).toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}
              </p>
            )}
          </div>
          <div className="flex items-center gap-2 shrink-0">
            {/* Share button */}
            <button
              ref={shareButtonRef}
              onClick={() => {
                if (!shareOpen && shareButtonRef.current) {
                  setShareRect(shareButtonRef.current.getBoundingClientRect());
                }
                setShareOpen((v) => !v);
              }}
              className={`inline-flex items-center gap-1.5 h-8 px-3 rounded-lg text-sm transition-all border font-body ${
                shareOpen
                  ? "text-white bg-[rgba(255,255,255,0.09)] border-[rgba(255,255,255,0.12)]"
                  : "text-[rgba(232,237,248,0.4)] hover:text-white hover:bg-[rgba(255,255,255,0.07)] border-transparent hover:border-[rgba(255,255,255,0.08)]"
              }`}
              aria-label="Share this trip story"
              aria-expanded={shareOpen}
            >
              <Share2 className="h-3.5 w-3.5" />
              Share
            </button>

            {/* Share popover — rendered via portal so it escapes any stacking context */}
            {shareOpen && shareRect && typeof document !== "undefined" && createPortal(
              <div
                ref={sharePopoverRef}
                className="fixed z-[9999] w-64 animate-fade-up"
                style={{
                  top: shareRect.bottom + 8,
                  right: window.innerWidth - shareRect.right,
                  animationDuration: "120ms",
                }}
              >
                {/* Arrow caret */}
                <div
                  className="absolute -top-[5px] right-3 w-2.5 h-2.5 bg-[#16161f] border-l border-t border-[rgba(255,255,255,0.1)] rotate-45"
                />

                <div className="rounded-2xl bg-[#16161f] border border-[rgba(255,255,255,0.1)] shadow-[0_20px_60px_rgba(0,0,0,0.7),0_0_0_1px_rgba(255,255,255,0.03)] overflow-hidden">
                  {/* Header */}
                  <div className="flex items-center justify-between px-4 pt-3.5 pb-2.5 border-b border-[rgba(255,255,255,0.07)]">
                    <span className="text-xs font-bold uppercase tracking-[0.15em] text-[rgba(232,237,248,0.3)] font-body">
                      Share story
                    </span>
                    <button
                      onClick={() => setShareOpen(false)}
                      className="w-5 h-5 rounded-md flex items-center justify-center text-[rgba(232,237,248,0.25)] hover:text-white hover:bg-[rgba(255,255,255,0.08)] transition-colors"
                    >
                      <X className="h-3 w-3" />
                    </button>
                  </div>

                  {/* Actions */}
                  <div className="p-1.5 space-y-0.5">
                    <button
                      onClick={handleCopyLink}
                      className="w-full flex items-center gap-3 px-3 py-2.5 rounded-xl text-left hover:bg-[rgba(255,255,255,0.06)] transition-colors group"
                    >
                      <div className="w-7 h-7 rounded-lg bg-[rgba(56,189,248,0.1)] flex items-center justify-center shrink-0 group-hover:bg-[rgba(56,189,248,0.18)] transition-colors">
                        <Link className="h-3.5 w-3.5 text-[#38bdf8]" />
                      </div>
                      <div>
                        <p className="text-sm font-semibold text-[rgba(232,237,248,0.85)] font-body leading-none">Copy link</p>
                        <p className="text-sm text-[rgba(232,237,248,0.35)] mt-0.5 font-body">Share the page URL</p>
                      </div>
                    </button>

                    <button
                      onClick={handleCopyText}
                      className="w-full flex items-center gap-3 px-3 py-2.5 rounded-xl text-left hover:bg-[rgba(255,255,255,0.06)] transition-colors group"
                    >
                      <div className="w-7 h-7 rounded-lg bg-[rgba(251,146,60,0.1)] flex items-center justify-center shrink-0 group-hover:bg-[rgba(251,146,60,0.18)] transition-colors">
                        <Copy className="h-3.5 w-3.5 text-[#fb923c]" />
                      </div>
                      <div>
                        <p className="text-sm font-semibold text-[rgba(232,237,248,0.85)] font-body leading-none">Copy story</p>
                        <p className="text-sm text-[rgba(232,237,248,0.35)] mt-0.5 font-body">All panels as text</p>
                      </div>
                    </button>
                  </div>

                  {/* Integrations divider */}
                  <div className="px-4 pt-2.5 pb-2 border-t border-[rgba(255,255,255,0.07)]">
                    <span className="text-[10px] font-bold uppercase tracking-[0.15em] text-[rgba(232,237,248,0.22)] font-body">
                      Send to
                    </span>
                    <input
                      type="text"
                      value={shareMessage}
                      onChange={(e) => setShareMessage(e.target.value)}
                      placeholder="Add a message…"
                      maxLength={500}
                      className="mt-2 w-full bg-[#0f1319] border border-[rgba(255,255,255,0.08)] rounded-lg px-2.5 py-1.5 text-xs text-[#e8edf8] font-body placeholder:text-[rgba(232,237,248,0.22)] focus:outline-none focus:border-[rgba(245,166,35,0.4)] transition-colors"
                    />
                  </div>

                  <div className="p-1.5 pt-0 space-y-0.5">
                    <button
                      onClick={handleShareToSlack}
                      disabled={sharing !== null}
                      className="w-full flex items-center gap-3 px-3 py-2.5 rounded-xl text-left hover:bg-[rgba(255,255,255,0.06)] transition-colors group disabled:opacity-50 disabled:cursor-not-allowed"
                    >
                      <div className="w-7 h-7 rounded-lg bg-[rgba(124,58,237,0.12)] flex items-center justify-center shrink-0 group-hover:bg-[rgba(124,58,237,0.22)] transition-colors">
                        {sharing === "slack" ? (
                          <Loader2 className="h-3.5 w-3.5 text-[#a78bfa] animate-spin" />
                        ) : (
                          <Hash className="h-3.5 w-3.5 text-[#a78bfa]" />
                        )}
                      </div>
                      <div>
                        <p className="text-sm font-semibold text-[rgba(232,237,248,0.85)] font-body leading-none">Share to Slack</p>
                        <p className="text-sm text-[rgba(232,237,248,0.35)] mt-0.5 font-body">Post to a channel</p>
                      </div>
                    </button>

                    <button
                      onClick={handleShareToTeams}
                      disabled={sharing !== null}
                      className="w-full flex items-center gap-3 px-3 py-2.5 rounded-xl text-left hover:bg-[rgba(255,255,255,0.06)] transition-colors group disabled:opacity-50 disabled:cursor-not-allowed"
                    >
                      <div className="w-7 h-7 rounded-lg bg-[rgba(37,99,235,0.12)] flex items-center justify-center shrink-0 group-hover:bg-[rgba(37,99,235,0.22)] transition-colors">
                        {sharing === "teams" ? (
                          <Loader2 className="h-3.5 w-3.5 text-[#60a5fa] animate-spin" />
                        ) : (
                          <MessageSquare className="h-3.5 w-3.5 text-[#60a5fa]" />
                        )}
                      </div>
                      <div>
                        <p className="text-sm font-semibold text-[rgba(232,237,248,0.85)] font-body leading-none">Share to Teams</p>
                        <p className="text-sm text-[rgba(232,237,248,0.35)] mt-0.5 font-body">Post to a channel</p>
                      </div>
                    </button>
                  </div>
                </div>
              </div>,
              document.body
            )}
            <button
              onClick={handleExport}
              disabled={exporting}
              className="inline-flex items-center gap-1.5 h-8 px-3 rounded-lg text-sm text-[rgba(232,237,248,0.4)] hover:text-white hover:bg-[rgba(255,255,255,0.07)] transition-all border border-transparent hover:border-[rgba(255,255,255,0.08)] font-body disabled:opacity-40 disabled:cursor-not-allowed"
              aria-label="Export this trip story as a PDF"
            >
              {exporting ? (
                <Loader2 className="h-3.5 w-3.5 animate-spin" />
              ) : (
                <Download className="h-3.5 w-3.5" />
              )}
              Export
            </button>
          </div>
        </div>
      )}

      {/* Tone selector + generate button */}
      <div className="bg-[rgba(255,255,255,0.04)] backdrop-blur-sm rounded-2xl border border-[rgba(255,255,255,0.08)] p-5 animate-fade-up" style={{ animationDelay: "60ms" }}>
        <div className="mb-5">
          <ToneSelector value={pendingTone} onChange={handleToneChange} disabled={generating} />
        </div>
        <button
          onClick={handleRegenerate}
          disabled={generating || loading || !trip}
          className="w-full h-12 rounded-xl text-sm font-display font-bold flex items-center justify-center gap-2 btn-amber disabled:opacity-50 disabled:cursor-not-allowed disabled:transform-none"
        >
          {generating ? (
            <>
              <Loader2 className="h-4 w-4 animate-spin" />
              Generating story…
            </>
          ) : (
            <>
              <RefreshCw className="h-4 w-4" />
              {story ? "Regenerate Story" : "Generate Trip Story"}
            </>
          )}
        </button>
        {!trip && (
          <p className="text-sm text-[rgba(232,237,248,0.3)] text-center mt-2.5 font-body">
            No trip loaded — the story will generate from cached data
          </p>
        )}
      </div>

      {/* Panels */}
      {(loading || generating) && !story ? (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
          {Array.from({ length: 4 }).map((_, i) => <PanelSkeleton key={i} index={i} />)}
        </div>
      ) : story ? (
        <>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
            {story.panels.map((panel, i) => (
              <ComicPanelCard
                key={panel.panelNumber}
                panel={panel}
                panelIndex={i}
                isEnriching={enriching}
              />
            ))}
          </div>

          {enriching && (
            <div className="flex items-center gap-2 text-sm text-[rgba(232,237,248,0.3)] px-1 font-body">
              <ImageIcon className="h-3 w-3 animate-pulse text-[#fb923c]/60" />
              Finding place photos…
            </div>
          )}

          {/* Story footer */}
          <div className="flex items-center justify-between text-sm text-[rgba(232,237,248,0.2)] px-1 border-t border-[rgba(255,255,255,0.07)] pt-4">
            <span className="font-body">
              FleetHappens · {story.panels.length} panels · {story.tone} tone
            </span>
            <span className="font-data">
              {new Date(story.createdAt).toLocaleTimeString()}
            </span>
          </div>
        </>
      ) : null}

      {/* Empty state */}
      {!loading && !generating && !story && (
        <div className="flex flex-col items-center justify-center py-20 text-center">
          <div className="rounded-2xl bg-[rgba(255,255,255,0.04)] border border-[rgba(255,255,255,0.07)] p-10 mb-5">
            <Sparkles className="h-10 w-10 text-[rgba(232,237,248,0.18)] mx-auto" />
          </div>
          <p className="font-display font-bold text-white text-xl mb-1.5">Your story is waiting</p>
          <p className="text-sm text-[rgba(232,237,248,0.38)] max-w-sm leading-relaxed font-body">
            Select a tone, optionally explore stop contexts on the dashboard for richer panels, then hit{" "}
            <span className="text-[#f5a623] font-semibold">&ldquo;Generate Trip Story&rdquo;</span> above.
          </p>
        </div>
      )}
    </div>
  );
}
