/**
 * POST /api/story/enrich-images
 *
 * Accepts an array of ComicPanels (as generated by /api/story/generate) and
 * returns them enriched with `image` payloads.
 *
 * This endpoint is called as a non-blocking second step AFTER the story text
 * has already been rendered — photo lookup never delays the initial story.
 *
 * On any error the original panels are returned so the story stays intact.
 *
 * Owner: Story Image Enrichment
 */

import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { enrichPanelImages } from "@/lib/story/image-enrichment";
import type { ComicPanel } from "@/types";

// ─── Request validation ───────────────────────────────────────────────────────

const MapAnchorSchema = z.object({ lat: z.number(), lon: z.number() });

const PanelSchema = z.object({
  panelNumber: z.number().int().min(1).max(4),
  sceneType: z.enum(["opening", "journey", "highlight", "arrival"]),
  locationName: z.string(),
  caption: z.string(),
  speechBubble: z.string().optional(),
  mapAnchor: MapAnchorSchema,
  timeLabel: z.string().optional(),
  distanceLabel: z.string().optional(),
  speedLabel: z.string().optional(),
  dwellLabel: z.string().optional(),
  // Accept (and preserve) any existing image field; the enricher will skip
  // panels that already have an image.
  image: z.any().optional(),
});

const RequestSchema = z.object({
  panels: z.array(PanelSchema).min(1).max(4),
});

// ─── Handler ──────────────────────────────────────────────────────────────────

export async function POST(req: NextRequest): Promise<NextResponse> {
  let body: unknown;
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ ok: false, error: "Invalid JSON" }, { status: 400 });
  }

  const parsed = RequestSchema.safeParse(body);
  if (!parsed.success) {
    return NextResponse.json(
      { ok: false, error: "Invalid request", details: parsed.error.errors },
      { status: 400 }
    );
  }

  try {
    const enriched = await enrichPanelImages(
      parsed.data.panels as ComicPanel[]
    );
    return NextResponse.json({ ok: true, panels: enriched });
  } catch (err) {
    // Unexpected error — return original panels so the story is never broken.
    console.error("[enrich-images] unexpected error:", err);
    return NextResponse.json({
      ok: true,
      panels: parsed.data.panels,
      warn: "Enrichment failed; returning original panels",
    });
  }
}
