/**
 * Zod schemas for the ComicStory system.
 * These are the single source of truth for both LLM output validation
 * and runtime type checking of the full assembled story.
 *
 * Owner: Comic Story Agent
 */

import { z } from "zod";

// ─── Primitives ───────────────────────────────────────────────────────────────

export const MapAnchorSchema = z.object({
  lat: z.number().min(-90).max(90),
  lon: z.number().min(-180).max(180),
});

export const SceneTypeSchema = z.enum([
  "opening",
  "journey",
  "highlight",
  "arrival",
]);

export const ComicToneSchema = z.enum(["guidebook", "playful", "cinematic"]);

// ─── StoryPanelImage (attached after enrichment, never from LLM) ──────────────

export const StoryPanelImageSchema = z.discriminatedUnion("kind", [
  z.object({
    kind: z.literal("place-photo"),
    imageUrl: z.string().url(),
    attribution: z.string().optional(),
    source: z.enum(["live", "cache"]),
    placeName: z.string().optional(),
  }),
  z.object({
    kind: z.literal("map"),
    source: z.literal("generated"),
  }),
  z.object({
    kind: z.literal("fallback"),
    icon: z.string().optional(),
    label: z.string().optional(),
    source: z.literal("fallback"),
  }),
]);

// ─── Area photo (curated gallery, not from LLM) ───────────────────────────────

export const AreaPhotoSchema = z.object({
  url: z.string().url(),
  caption: z.string().optional(),
  attribution: z.string().optional(),
});

// ─── Full ComicPanel (assembled by the API route) ─────────────────────────────

export const ComicPanelSchema = z.object({
  panelNumber: z.number().int().min(1).max(4),
  sceneType: SceneTypeSchema,
  locationName: z.string().min(1).max(120),
  caption: z.string().min(10).max(400),
  speechBubble: z.string().max(120).optional(),
  mapAnchor: MapAnchorSchema,
  timeLabel: z.string().optional(),
  distanceLabel: z.string().optional(),
  speedLabel: z.string().optional(),
  dwellLabel: z.string().optional(),
  /** Populated by the image-enrichment step — not generated by the LLM. */
  image: StoryPanelImageSchema.optional(),
  /** Curated area photos for the gallery toggle view. */
  areaPhotos: z.array(AreaPhotoSchema).optional(),
});

// ─── Full ComicStory (what the API returns) ───────────────────────────────────

export const ComicStorySchema = z.object({
  id: z.string().min(1),
  tripId: z.string().min(1),
  title: z.string().min(3).max(100),
  tone: ComicToneSchema,
  panels: z.array(ComicPanelSchema).length(4),
  createdAt: z.string().datetime(),
});

// ─── LLM output shape (only the creative fields the model generates) ──────────
// The route assembles the rest (id, tripId, tone, mapAnchor, labels) from
// structured beat data — the LLM never makes up coordinates or metrics.

export const LLMPanelOutputSchema = z.object({
  panelNumber: z.number().int().min(1).max(4),
  locationName: z.string().min(1).max(120),
  caption: z.string().min(10).max(400),
  speechBubble: z.string().max(120).optional(),
});

export const LLMStoryOutputSchema = z.object({
  title: z.string().min(3).max(100),
  panels: z
    .array(LLMPanelOutputSchema)
    .min(4)
    .max(4)
    .refine(
      (panels) => {
        const nums = panels.map((p) => p.panelNumber).sort();
        return (
          nums.length === 4 &&
          nums[0] === 1 &&
          nums[1] === 2 &&
          nums[2] === 3 &&
          nums[3] === 4
        );
      },
      { message: "panels must be numbered 1–4 with no duplicates" }
    ),
});

// ─── Inferred TypeScript types ────────────────────────────────────────────────

export type ComicStoryValidated = z.infer<typeof ComicStorySchema>;
export type LLMStoryOutput = z.infer<typeof LLMStoryOutputSchema>;
export type LLMPanelOutput = z.infer<typeof LLMPanelOutputSchema>;
